[project]
name = "bedrock-knowledge-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aws-cdk-lib>=2.189.0",
    "boto3>=1.37.31",
    "streamlit>=1.44.1",
    "streamlit-extras>=0.6.0",
]
